name: Push to Main

on:
  push:
    branches: [ "main" ]

permissions:
  actions: read
  packages: write
  contents: write
  security-events: write
  pull-requests: write
  checks: write
  id-token: write

jobs:
  codeql:
    name: CodeQL - ${{ matrix.language }}
    uses: DWSR/actions/.github/workflows/codeql.yml@main
    strategy:
      matrix:
        include:
          - language: go
            build-mode: autobuild
          - language: actions
            build-mode: none
    with:
      language: "${{ matrix.language }}"
      build-mode: "${{ matrix.build-mode }}"

  golangci-lint:
    name: golangci-lint
    uses: DWSR/actions/.github/workflows/golangci-lint.yml@main
    if: github.event_name != 'schedule'

  tests:
    name: Tests
    uses: DWSR/actions/.github/workflows/go-test-single.yml@main
    if: github.event_name != 'schedule'

  render-kube-app:
    name: Render Kubernetes manifests - ${{ matrix.path }}
    uses: DWSR/actions/.github/workflows/render-kube-app.yml@main
    strategy:
      matrix:
        include:
          - path: overlays/live
            create-bundle: true
          - path: overlays/test
            create-bundle: false
    with:
      path: "${{ matrix.path }}"
      create-bundle: "${{ matrix.create-bundle }}"
