name: Push to Main

on:
  push:
    branches: [ "main" ]

permissions:
  actions: read
  packages: write
  contents: write
  security-events: write
  pull-requests: write
  checks: write
  id-token: write

jobs:
  codeql:
    name: CodeQL - ${{ matrix.language }}
    uses: DWSR/actions/.github/workflows/codeql.yml@main
    strategy:
      matrix:
        include:
          - language: go
            build-mode: autobuild
          - language: actions
            build-mode: none
    with:
      language: "${{ matrix.language }}"
      build-mode: "${{ matrix.build-mode }}"

  golangci-lint:
    name: golangci-lint
    uses: DWSR/actions/.github/workflows/golangci-lint.yml@main

  tests:
    name: Tests
    uses: DWSR/actions/.github/workflows/go-test-single.yml@main

  render-live:
    name: Render Kubernetes manifests - live
    uses: DWSR/actions/.github/workflows/render-kube-app.yml@main
    needs: [tests]
    with:
      path: overlays/live
      create-bundle: true

  render-test:
    name: Render Kubernetes manifests - test
    uses: DWSR/actions/.github/workflows/render-kube-app.yml@main
    with:
      path: overlays/test

  update-infra-repo:
    name: Update Infra Repo
    runs-on: ubuntu-latest
    needs: [render-live]
    steps:
      - name: Get infra bot app token
        id: app-token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
        with:
          app-id: "${{ secrets.INFRA_BOT_APP_ID }}"
          private-key: "${{ secrets.INFRA_BOT_PRIVATE_KEY }}"
          owner: DWSR
          repositories: infra
      - name: Dispatch workflow
        run: |
          gh workflow run \
            'Update Kubernetes App' \
            --repo DWSR/infra \
            --field 'ref=${{ github.ref }}' \
            --field 'bundle-with-digest=${{ needs.render-live.outputs.bundle-with-digest }}' \
            --field 'repo-name=${{ github.repository }}'
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
